site_name: Univapay-Python SDK
site_description: Documentation for the Univapay-Python SDK (unofficial)
site_url: ""
repo_url: https://github.com/NoManNayeem/Univapay-Python
theme:
  name: material
  features:
    - navigation.sections
    - navigation.instant
    - content.code.copy
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_if_no_docstring: true
            heading_level: 2
nav:
  - Home: docs/index.md
  - Quickstart: docs/Quickstart.md
  - Using with Python: docs/Using-with-Python.md
  - Using with Django & DRF: docs/Using-with-Django-and-DRF.md
  - Using with FastAPI: docs/Using-with-FastAPI.md
  - API Reference:
      - SDK API: docs/API.md

