site_name: Univapay-Python SDK
site_description: Documentation for the Univapay-Python SDK (unofficial)
site_url: "https://github.com/NoManNayeem/Univapay-Python"
repo_url: https://github.com/NoManNayeem/Univapay-Python
theme:
  name: material
  features:
    - navigation.sections
    - navigation.instant
    - content.code.copy
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_if_no_docstring: true
            heading_level: 2
nav:
  - Home: index.md
  - Quickstart: Quickstart.md
  - Configuration: Configuration.md
  - Widgets: Widgets.md
  - Webhooks: Webhooks.md
  - Examples: Examples.md
  - Errors & Debugging: Errors-and-Debugging.md
  - Using with Python: Using-with-Python.md
  - Using with Django & DRF: Using-with-Django-and-DRF.md
  - Using with FastAPI: Using-with-FastAPI.md
  - API Reference:
      - SDK API: API.md
